apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: emerald-charge
spec:
  selector:
    app: booking-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
