apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: emerald-charge
spec:
  selector:
    app: session-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
